# United States of America Python Dictionary to translate States,
# Districts & Territories to Two-Letter codes and vice versa.
#
# Canonical URL: https://gist.github.com/rogerallen/1583593
#
# Dedicated to the public domain.  To the extent possible under law,
# Roger Allen has waived all copyright and related or neighboring
# rights to this code.  Data originally from Wikipedia at the url:
# https://en.wikipedia.org/wiki/ISO_3166-2:US
#
# Automatically Generated 2021-09-11 18:04:36 via Jupyter Notebook from
# https://gist.github.com/rogerallen/d75440e8e5ea4762374dfd5c1ddf84e0

us_states = {
    "Alabama": {"abb": "AL", "fips": "01"},
    "Alaska": {"abb": "AK", "fips": "02"},
    "Arizona": {"abb": "AZ", "fips": "04"},
    "Arkansas": {"abb": "AR", "fips": "05"},
    "California": {"abb": "CA", "fips": "06"},
    "Colorado": {"abb": "CO", "fips": "08"},
    "Connecticut": {"abb": "CT", "fips": "09"},
    "Delaware": {"abb": "DE", "fips": "10"},
    "Florida": {"abb": "FL", "fips": "12"},
    "Georgia": {"abb": "GA", "fips": "13"},
    "Hawaii": {"abb": "HI", "fips": "15"},
    "Idaho": {"abb": "ID", "fips": "16"},
    "Illinois": {"abb": "IL", "fips": "17"},
    "Indiana": {"abb": "IN", "fips": "18"},
    "Iowa": {"abb": "IA", "fips": "19"},
    "Kansas": {"abb": "KS", "fips": "20"},
    "Kentucky": {"abb": "KY", "fips": "21"},
    "Louisiana": {"abb": "LA", "fips": "22"},
    "Maine": {"abb": "ME", "fips": "23"},
    "Maryland": {"abb": "MD", "fips": "24"},
    "Massachusetts": {"abb": "MA", "fips": "25"},
    "Michigan": {"abb": "MI", "fips": "26"},
    "Minnesota": {"abb": "MN", "fips": "27"},
    "Mississippi": {"abb": "MS", "fips": "28"},
    "Missouri": {"abb": "MO", "fips": "29"},
    "Montana": {"abb": "MT", "fips": "30"},
    "Nebraska": {"abb": "NE", "fips": "31"},
    "Nevada": {"abb": "NV", "fips": "32"},
    "New Hampshire": {"abb": "NH", "fips": "33"},
    "New Jersey": {"abb": "NJ", "fips": "34"},
    "New Mexico": {"abb": "NM", "fips": "25"},
    "New York": {"abb": "NY", "fips": "36"},
    "North Carolina": {"abb": "NC", "fips": "37"},
    "North Dakota": {"abb": "ND", "fips": "38"},
    "Ohio": {"abb": "OH", "fips": "39"},
    "Oklahoma": {"abb": "OK", "fips": "40"},
    "Oregon": {"abb": "OR", "fips": "41"},
    "Pennsylvania": {"abb": "PA", "fips": "42"},
    "Rhode Island": {"abb": "RI", "fips": "44"},
    "South Carolina": {"abb": "SC", "fips": "45"},
    "South Dakota": {"abb": "SD", "fips": "46"},
    "Tennessee": {"abb": "TN", "fips": "47"},
    "Texas": {"abb": "TX", "fips": "48"},
    "Utah": {"abb": "UT", "fips": "49"},
    "Vermont": {"abb": "VT", "fips": "50"},
    "Virginia": {"abb": "VA", "fips": "51"},
    "Washington": {"abb": "WA", "fips": "53"},
    "West Virginia": {"abb": "WV", "fips": "54"},
    "Wisconsin": {"abb": "WI", "fips": "55"},
    "Wyoming": {"abb": "WY", "fips": "56"},
    "District of Columbia": {"abb": "DC", "fips": "11"},
    "American Samoa": {"abb": "AS", "fips": "00"},
    "Guam": {"abb": "GU", "fips": "00"},
    "Northern Mariana Islands": {"abb": "MP", "fips": "00"},
    "Puerto Rico": {"abb": "PR", "fips": "72"},
    "United States Minor Outlying Islands": {"abb": "UM", "fips": "00"},
    "U.S. Virgin Islands": {"abb": "VI", "fips": "00"},
}
stateFipsToName = {
    "01": "Alabama",
    "02": "Alaska",
    "04": "Arizona",
    "05": "Arkansas",
    "06": "California",
    "08": "Colorado",
    "09": "Connecticut",
    "10": "Delaware",
    "11": "District of Columbia",
    "12": "Florida",
    "13": "Georgia",
    "15": "Hawaii",
    "16": "Idaho",
    "17": "Illinois",
    "18": "Indiana",
    "19": "Iowa",
    "20": "Kansas",
    "21": "Kentucky",
    "22": "Louisiana",
    "23": "Maine",
    "24": "Maryland",
    "25": "Massachusetts",
    "26": "Michigan",
    "27": "Minnesota",
    "28": "Mississippi",
    "29": "Missouri",
    "30": "Montana",
    "31": "Nebraska",
    "32": "Nevada",
    "33": "New Hampshire",
    "34": "New Jersey",
    "35": "New Mexico",
    "36": "New York",
    "37": "North Carolina",
    "38": "North Dakota",
    "39": "Ohio",
    "40": "Oklahoma",
    "41": "Oregon",
    "42": "Pennsylvania",
    "44": "Rhode Island",
    "45": "South Carolina",
    "46": "South Dakota",
    "47": "Tennessee",
    "48": "Texas",
    "49": "Utah",
    "50": "Vermont",
    "51": "Virginia",
    "53": "Washington",
    "54": "West Virginia",
    "55": "Wisconsin",
    "56": "Wyoming",
    "72": "Puerto Rico",
}
us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
}

# invert the dictionary
abbrev_to_us_state = dict(map(reversed, us_state_to_abbrev.items()))
